version: "3"
services:
  property_service:
    build: 
      context: ../..
      dockerfile: ./examples/federation/property-service/Dockerfile
    hostname: property
    ports:
      - "4000"
  reviews_service:
    build: 
      context: ../..
      dockerfile: ./examples/federation/reviews-service/Dockerfile
    hostname: reviews
    ports:
      - "4000"
  gateway:
    build: 
      context: ../..
      dockerfile: ./examples/federation/gateway/Dockerfile
    ports:
      - "4000:4000"
    links: 
      - property_service:property
      - reviews_service:reviews
    depends_on:
      - property_service
      - reviews_service